spring:
  application:
    name: payment-service
  datasource:
    url: ${DATABASE_URL_ORDER_PLATFORM}
    username: ${DATABASE_USERNAME_ORDER_PLATFORM}
    password: ${DATABASE_PASSWORD_ORDER_PLATFORM}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

payment-service:
  payment:
    kafka:
      transaction-created-topic: ${KAFKA_TRANSACTION_CREATED_TOPIC}
      group-id: ${KAFKA_PAYMENT_SERVICE_GROUP_ID}
      payment-notification-topic: ${KAFKA_PAYMENT_NOTIFICATION_TOPIC}
    paypal:
      base-url: https://api-m.sandbox.paypal.com
      client-id: ${PAYPAL_CLIENT_ID}
      client-secret: ${PAYPAL_SECRETS}

logging:
  level:
    com.mihaela.orderplatform: INFO



